SUPABASE_URL = "https://zchpsallohlxqjtmrvkd.supabase.co"
SUPABASE_KEY = "sb_publishable_d14dhEGJZk77Nwhr1E4tKA_B9aqBAnk"
SUPABASE_SERVICE_KEY="sb_secret_4JnmybVQHS2F4jeHjjat5g_kwV908JR"
PTOSR_API="https://ptosr.pelindo.co.id/ScheduleBoard/GetData?kd_cabang=61&kd_terminal=601"
